# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160509_1903'),
        ('accounts', '0016_auto_20160411_2213'),
    ]

    operations = [
    ]
