# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge'),
        ('accounts', '0018_profile_new_question_notifications'),
    ]

    operations = [
    ]
